version: '3.8'

services:
  whatsappbot:
    build: .
    container_name: whatsappbot
    ports:
      - "8080:8080"         # Expose le port local 8080 vers le conteneur
    env_file:
      - .env                # Charge les variables d’environnement
    command: python server.py
