name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout le code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Linter (py_compile)
        run: |
          python -m compileall core/
          python -m compileall main.py

      - name: Vérification des dépendances
        run: pip install -r requirements.txt

      - name: Construction de l’image Docker
        run: docker build -t whatsappbot .

      - name: Lancer le conteneur avec les secrets
        run: |
          docker run --rm \
            -e GROQ_API_KEY=${{ secrets.GROQ_API_KEY }} \
            -e TWILIO_SID=${{ secrets.TWILIO_SID }} \
            -e TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }} \
            -e TWILIO_WHATSAPP_NUMBER=${{ secrets.TWILIO_WHATSAPP_NUMBER }} \
            -e RECIPIENT_WHATSAPP_NUMBER=${{ secrets.RECIPIENT_WHATSAPP_NUMBER }} \
            whatsappbot python main.py
